version: '3'

services:
  db:
    container_name: db
    restart: always
    image: postgres:15
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=central
    ports:
      - "5432:5432"

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:rw
      - ./mosquitto/log/:/mosquitto/log/
      - data:/mosquitto/data/
    depends_on:
      - db

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  app:
    build: .
    container_name: relay_central_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mqtt
    volumes:
      - ./src:/app/src

volumes:
  data:
  postgres_data:
