-- Docker will create the database central
\c central;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
username VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(60) NOT NULL -- Use crypt
);

CREATE TABLE IF NOT EXISTS device_types (
id SERIAL PRIMARY KEY,
text VARCHAR(20) NOT NULL UNIQUE,
userId INT NOT NULL,

FOREIGN KEY(userId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS rooms (
id SERIAL PRIMARY KEY,
name VARCHAR(20) NOT NULL UNIQUE,
userId INT NOT NULL,

FOREIGN KEY(userId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS relays (
id SERIAL PRIMARY KEY,
deviceTypeId INT NOT NULL,
name VARCHAR(20) NOT NULL UNIQUE,
topic VARCHAR(70) NOT NULL,
state BOOLEAN DEFAULT false,

FOREIGN KEY(deviceTypeId) REFERENCES device_types(id)
);

CREATE TABLE IF NOT EXISTS device_status(
id SERIAL PRIMARY KEY,
relayId INT NOT NULL,
status BOOLEAN DEFAULT false,
status_changed_at TIMESTAMP,

FOREIGN KEY(relayId) REFERENCES relays(id)
);

GRANT SELECT ON relays TO postgres;
